name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  BUILD_TESTS: on
  CODE_COVERAGE: on

jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y libv8-dev lcov

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DBUILD_TESTS=${{env.BUILD_TESTS}} \
            -DCODE_COVERAGE=${{env.CODE_COVERAGE}}

      - name: Build
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          cmake --build ${{github.workspace}}/build \
            --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Coverage
        working-directory: ${{github.workspace}}/build
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/deps/*' '*/_deps/*' '*/test/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
