name: Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cmake-fetchcontent:
    name: "CMake FetchContent"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y libv8-dev

      - name: Configure CMake FetchContent
        run: |
          cmake -B ${{github.workspace}}/build \
            test/installer/cmake-fetchcontent

      - name: Build FetchContent
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: cmake --build ${{github.workspace}}/build

      - name: Test FetchContent
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

  cmake-findpackage:
    name: "CMake FindPackage"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y libv8-dev

      - name: Configure CMake Library
        run: cmake -B ${{github.workspace}}/build

      - name: Build Library
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: cmake --build ${{github.workspace}}/build

      - name: Install Library
        working-directory: ${{github.workspace}}/build
        run: sudo make install

      - name: Configure CMake FindPackage
        run: |
          cmake -E remove_directory ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build \
            test/installer/cmake-findpackage

      - name: Build FindPackage
        run: cmake --build ${{github.workspace}}/build

      - name: Test FindPackage
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
